#
# plpython.po
#   Italian message translation file for plpython
#
# For development and bug report please use:
# https://github.com/dvarrazzo/postgresql-it
#
# Copyright (C) 2012-2017 PostgreSQL Global Development Group
# Copyright (C) 2010, Associazione Culturale ITPUG
#
# Daniele Varrazzo <daniele.varrazzo@gmail.com>, 2012-2017.
# Flavio Spada <f.spada@sbv.mi.it>
#
# This file is distributed under the same license as the PostgreSQL package.
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL) 11\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2018-10-08 14:07+0000\n"
"PO-Revision-Date: 2018-10-08 23:11+0100\n"
"Last-Translator: Daniele Varrazzo <daniele.varrazzo@gmail.com>\n"
"Language-Team: https://github.com/dvarrazzo/postgresql-it\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Poedit 2.0.6\n"

#: plpy_cursorobject.c:101
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor richiede una query o un piano"

#: plpy_cursorobject.c:184
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor richiede una sequenza come secondo argomento"

#: plpy_cursorobject.c:200 plpy_spi.c:211
#, c-format
msgid "could not execute plan"
msgstr "esecuzione del piano fallita"

#: plpy_cursorobject.c:203 plpy_spi.c:214
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Attesa sequenza di %d argomento, ricevuti %d: %s"
msgstr[1] "Attesa sequenza di %d argomenti, ricevuti %d: %s"

#: plpy_cursorobject.c:352
#, c-format
msgid "iterating a closed cursor"
msgstr "iterazione di un cursore chiuso"

#: plpy_cursorobject.c:360 plpy_cursorobject.c:426
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "iterazione di un cursore in una sotto-transazione interrotta"

#: plpy_cursorobject.c:418
#, c-format
msgid "fetch from a closed cursor"
msgstr "lettura da un cursore chiuso"

#: plpy_cursorobject.c:461 plpy_spi.c:409
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "il risultato della query ha troppe righe per una lista Python"

#: plpy_cursorobject.c:512
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "chiusura di un cursore in una sotto-transazione interrotta"

#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:559
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:142
#, c-format
msgid "unsupported set function return mode"
msgstr "modalità di ritorno della funzione set non supportata"

#: plpy_exec.c:143
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "Le funzioni PL/Python che restituiscono insiemi supportano la restituzione di un solo valore per chiamata."

#: plpy_exec.c:156
#, c-format
msgid "returned object cannot be iterated"
msgstr "l'oggetto restituito non può essere iterato"

#: plpy_exec.c:157
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "Le funzioni PL/Python che restituiscono insiemi devono restituire un oggetto iterabile."

#: plpy_exec.c:171
#, c-format
msgid "error fetching next item from iterator"
msgstr "errore nell'ottenere l'elemento successivo dall'iteratore"

#: plpy_exec.c:214
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "la procedura PL/Python non ha restituito None"

#: plpy_exec.c:218
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "la funzione PL/Python che restituisce \"void\" non ha restituito None"

#: plpy_exec.c:374 plpy_exec.c:400
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "la prodedura trigger ha restituito un valore inatteso"

#: plpy_exec.c:375
#, c-format
msgid "Expected None or a string."
msgstr "Atteso None o una stringa."

#: plpy_exec.c:390
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "la funzione trigger PL/Python ha restituito \"MODIFY\" in un trigger DELETE -- ignorato"

#: plpy_exec.c:401
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Atteso None, \"OK\", \"SKIP\", o \"MODIFY\"."

#: plpy_exec.c:451
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "PyList_SetItem() è fallita durante l'impostazione degli argomenti"

#: plpy_exec.c:455
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "PyDict_SetItemString() è fallita durante l'impostazione degli argomenti"

#: plpy_exec.c:467
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "la funzione che restituisce un record è chiamata in un contesto che non può accettare il tipo record"

#: plpy_exec.c:684
#, c-format
msgid "while creating return value"
msgstr "durante la creazione del valore da restituire"

#: plpy_exec.c:909
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] cancellato, non è possibile modificare la riga"

#: plpy_exec.c:914
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] non è un dizionario"

#: plpy_exec.c:941
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "la chiave di dizionario TD[\"new\"] alla posizione %d non è una stringa"

#: plpy_exec.c:948
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "la chiave \"%s\" trovata in TD[\"new\"] non esiste come colonna nella riga del trigger"

#: plpy_exec.c:953
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "non è possibile impostare l'attributo di sistema \"%s\""

#: plpy_exec.c:1011
#, c-format
msgid "while modifying trigger row"
msgstr "durante la modifica della riga trigger"

#: plpy_exec.c:1072
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "interruzione forzata di una sotto-transazione che non è terminata"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "c'è più di una libreria Python presente nella sessione"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Solo una versione maggiore di Python può essere usata in una sessione."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "errore non catturato durante l'inizializzazione"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "importazione del modulo \"__main__\""

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "inizializzazione delle variabili globali fallita"

#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "procedura PL/Python \"%s\""

#: plpy_main.c:402
#, c-format
msgid "PL/Python function \"%s\""
msgstr "funzione PL/Python \"%s\""

#: plpy_main.c:410
#, c-format
msgid "PL/Python anonymous code block"
msgstr "blocco di codice anonimo in PL/Python"

#: plpy_plpymodule.c:192 plpy_plpymodule.c:195
#, c-format
msgid "could not import \"plpy\" module"
msgstr "importazione del modulo \"plpy\" fallita"

#: plpy_plpymodule.c:210
#, c-format
msgid "could not create the spiexceptions module"
msgstr "creazione del modulo spiexceptions fallita"

#: plpy_plpymodule.c:218
#, c-format
msgid "could not add the spiexceptions module"
msgstr "aggiunta del modulo spiexceptions fallita"

#: plpy_plpymodule.c:286
#, c-format
msgid "could not generate SPI exceptions"
msgstr "generazione delle eccezioni SPI fallita"

#: plpy_plpymodule.c:454
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "non è stato possibile espandere gli argomenti in plpy.elog"

#: plpy_plpymodule.c:463
msgid "could not parse error message in plpy.elog"
msgstr "non è stato possibile interpretare il messaggio di errore in plpy.elog"

#: plpy_plpymodule.c:480
#, c-format
msgid "argument 'message' given by name and position"
msgstr "parametro 'message' dato con nome e posizione"

#: plpy_plpymodule.c:507
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' è un nome di argomento non valido per questa funzione"

#: plpy_plpymodule.c:518 plpy_plpymodule.c:524
#, c-format
msgid "invalid SQLSTATE code"
msgstr "codice SQLSTATE non valido"

#: plpy_procedure.c:230
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "le funzioni trigger possono essere chiamate esclusivamente da trigger"

#: plpy_procedure.c:234
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "le funzioni PL/Python non possono restituire il tipo %s"

#: plpy_procedure.c:312
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "le funzioni PL/Python non possono accettare il tipo %s"

#: plpy_procedure.c:402
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "compilazione della funzione PL/Python \"%s\" fallita"

#: plpy_procedure.c:405
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "compilazione del blocco di codice anonimo PL/Python fallita"

#: plpy_resultobject.c:150 plpy_resultobject.c:176 plpy_resultobject.c:202
#, c-format
msgid "command did not produce a result set"
msgstr "il comando non ha prodotto risultati"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "il secondo argomento di plpy.prepare deve essere una sequenza"

#: plpy_spi.c:104
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: il nome del tipo nella posizione %d non è una stringa"

#: plpy_spi.c:176
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute si aspetta una query o un plan"

#: plpy_spi.c:195
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute richiede una sequenza come secondo argomento"

#: plpy_spi.c:305
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan ha fallito: %s"

#: plpy_spi.c:347
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute ha fallito: %s"

#: plpy_subxactobject.c:122
#, c-format
msgid "this subtransaction has already been entered"
msgstr "si è già entrati in questa sotto-transazione"

#: plpy_subxactobject.c:128 plpy_subxactobject.c:186
#, c-format
msgid "this subtransaction has already been exited"
msgstr "si è già usciti da questa sotto-transazione"

#: plpy_subxactobject.c:180
#, c-format
msgid "this subtransaction has not been entered"
msgstr "non si è entrati in questa sotto-transazione"

#: plpy_subxactobject.c:192
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "non c'è nessuna transazione da cui uscire"

#: plpy_typeio.c:591
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "importazione di un modulo per il costrutto Decimal fallita"

#: plpy_typeio.c:595
#, c-format
msgid "no Decimal attribute in module"
msgstr "attributo Decimal non trovato nel modulo"

#: plpy_typeio.c:601
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "conversione da numeric a Decimal fallita"

#: plpy_typeio.c:908
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "creazione della rappresentazione in byte dell'oggetto Python fallita"

#: plpy_typeio.c:1056
#, c-format
msgid "could not create string representation of Python object"
msgstr "creazione della rappresentazione stringa dell'oggetto Python fallita"

#: plpy_typeio.c:1067
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "conversione dell'oggetto Python in cstring fallita: la rappresentazione stringa Python sembra contenere byte null"

#: plpy_typeio.c:1176
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "il numero di dimensioni dell'array supera il massimo consentito (%d)"

#: plpy_typeio.c:1180
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "errore nel determinare la lunghezza della sequenza per il valore di ritorno della funzione"

#: plpy_typeio.c:1183 plpy_typeio.c:1187
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "la dimensione dell'array supera il massimo consentito"

#: plpy_typeio.c:1213
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "il valore restituito dalla funzione con tipo restituito array non è una sequenza Python"

#: plpy_typeio.c:1259
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "lunghezza errata della sequenza interna: la lunghezza è %d ma era atteso %d"

#: plpy_typeio.c:1261
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr "Per costruire un array multidimensionale le sequenze interne devono avere tutte la stessa lunghezza."

#: plpy_typeio.c:1340
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "letterale di record non corretto: \"%s\""

#: plpy_typeio.c:1341
#, c-format
msgid "Missing left parenthesis."
msgstr "Parentesi aperta mancante."

#: plpy_typeio.c:1342 plpy_typeio.c:1543
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Per restutuire un tipo composito in un array, restituisci il tipo composito come tupla Python, per esempio \"[('foo',)]\" "

#: plpy_typeio.c:1389
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la chiave \"%s\" non è stata trovata nel dizionario"

#: plpy_typeio.c:1390
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "Per restituire null in una colonna, inserire nella mappa il valore None con una chiave chiamata come la colonna."

#: plpy_typeio.c:1443
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "la lunghezza della sequenza ritornata non rispetta il numero di colonne presenti nella riga"

#: plpy_typeio.c:1541
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "l'attributo \"%s\" non esiste nell'oggetto Python"

#: plpy_typeio.c:1544
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "Per restituire null in una colonna, l'oggetto restituito deve avere un attributo chiamato come la colonna con valore None."

#: plpy_util.c:35
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "conversione dell'oggetto Unicode Python in byte fallita"

#: plpy_util.c:41
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "estrazione dei byte dalla stringa codificata fallita"
