# LANGUAGE message translation file for plpython
# Copyright (C) 2010 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: plpython (PostgreSQL) 12\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2019-05-22 17:56+0800\n"
"PO-Revision-Date: 2019-06-04 18:00+0800\n"
"Last-Translator: Jie Zhang <zhangjie2@cn.fujitsu.com>\n"
"Language-Team: Chinese (Simplified) <zhangjie2@cn.fujitsu.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: zh_CN\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Poedit 1.5.7\n"

#: plpy_cursorobject.c:78
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor期望一个查询或一个计划"

#: plpy_cursorobject.c:161
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor将一个序列作为它的第二个参数"

#: plpy_cursorobject.c:177 plpy_spi.c:211
#, c-format
msgid "could not execute plan"
msgstr "无法执行计划"

#: plpy_cursorobject.c:180 plpy_spi.c:214
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "期望%d序列参数,但是得到%d: %s"

#: plpy_cursorobject.c:329
#, c-format
msgid "iterating a closed cursor"
msgstr "遍历一个关闭的游标"

#: plpy_cursorobject.c:337 plpy_cursorobject.c:403
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "在终止的子事务里遍历一个游标"

#: plpy_cursorobject.c:395
#, c-format
msgid "fetch from a closed cursor"
msgstr "从关闭的游标里获取结果"

#: plpy_cursorobject.c:438 plpy_spi.c:409
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "查询结果中的行太多，无法放在一个Python列表中"

#: plpy_cursorobject.c:490
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "在终止的子事务里关闭一个游标"

#: plpy_elog.c:129 plpy_elog.c:130 plpy_plpymodule.c:553
#, c-format
msgid "%s"
msgstr "%s"

#: plpy_exec.c:143
#, c-format
msgid "unsupported set function return mode"
msgstr "不支持集合函数返回模式"

#: plpy_exec.c:144
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr "PL/Python集合返回函数只支持在每次调用时返回一个值。"

#: plpy_exec.c:157
#, c-format
msgid "returned object cannot be iterated"
msgstr "所返回的对象无法迭代"

#: plpy_exec.c:158
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "PL/Python集合返回函数必须返回一个可迭代的对象."

#: plpy_exec.c:172
#, c-format
msgid "error fetching next item from iterator"
msgstr "当从迭代器中取回下一个成员时出现错误"

#: plpy_exec.c:215
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "PL/Python过程没有返回None"

#: plpy_exec.c:219
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "返回类型为\"void\"的PL/Python函数不返回None"

#: plpy_exec.c:375 plpy_exec.c:401
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "在触发器存储过程出现非期望的返回值"

#: plpy_exec.c:376
#, c-format
msgid "Expected None or a string."
msgstr "期望空值或一个字符串"

#: plpy_exec.c:391
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "在DELETE触发器中的PL/Python 触发器函数返回 \"MODIFY\"  -- 忽略"

#: plpy_exec.c:402
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "期望None, \"OK\", \"SKIP\", 或\"MODIFY\""

#: plpy_exec.c:452
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "当设置参数的同时, 执行PyList_SetItem()失败"

#: plpy_exec.c:456
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "当设置参数的同时, 执行PyDict_SetItemString()失败"

#: plpy_exec.c:468
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr "返回值类型是记录的函数在不接受使用记录类型的环境中调用"

#: plpy_exec.c:685
#, c-format
msgid "while creating return value"
msgstr "同时在创建返回值"

#: plpy_exec.c:919
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] 已删除，无法修改记录"

#: plpy_exec.c:924
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"]不是一个字典"

#: plpy_exec.c:951
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "在顺序位置%d的TD[\"new\"]字典键值不是字符串"

#: plpy_exec.c:958
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr "在 TD[\"new\"]中找到的键 \"%s\"在正在触发的记录中不是作为列而存在."

#: plpy_exec.c:963
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "不能设置系统属性\"%s\""

#: plpy_exec.c:968
#, c-format
msgid "cannot set generated column \"%s\""
msgstr "无法设置生成的列 \"%s\""

#: plpy_exec.c:1026
#, c-format
msgid "while modifying trigger row"
msgstr "同时正在修改触发器记录"

#: plpy_exec.c:1087
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "强行终止一个还未退出的子事务"

#: plpy_main.c:125
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "会话中存在多个Python库"

#: plpy_main.c:126
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "一个会话中只能使用一个Python主版本."

#: plpy_main.c:142
#, c-format
msgid "untrapped error in initialization"
msgstr "在初始化过程中出现无法捕获的错误"

#: plpy_main.c:165
#, c-format
msgid "could not import \"__main__\" module"
msgstr "无法导入模块\"__main__\" "

#: plpy_main.c:174
#, c-format
msgid "could not initialize globals"
msgstr "无法初始化全局变量"

#: plpy_main.c:399
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "PL/Python过程\"%s\""

#: plpy_main.c:402
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python函数\"%s\""

#: plpy_main.c:410
#, c-format
msgid "PL/Python anonymous code block"
msgstr "PL/Python匿名代码块"

#: plpy_plpymodule.c:186 plpy_plpymodule.c:189
#, c-format
msgid "could not import \"plpy\" module"
msgstr "无法导入模块\"plpy\" "

#: plpy_plpymodule.c:204
#, c-format
msgid "could not create the spiexceptions module"
msgstr "无法创建spiexceptions模块"

#: plpy_plpymodule.c:212
#, c-format
msgid "could not add the spiexceptions module"
msgstr "无法添加spiexceptions模块 "

#: plpy_plpymodule.c:280
#, c-format
msgid "could not generate SPI exceptions"
msgstr "无法产生SPI异常"

#: plpy_plpymodule.c:448
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "无法解析plpy.elog中的参数"

#: plpy_plpymodule.c:457
msgid "could not parse error message in plpy.elog"
msgstr "无法解析在plpy.elog中的错误消息"

#: plpy_plpymodule.c:474
#, c-format
msgid "argument 'message' given by name and position"
msgstr "由名称和位置提供的参数'message'"

#: plpy_plpymodule.c:501
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "对于这个函数，'%s'是一个无效的关键词参数"

#: plpy_plpymodule.c:512 plpy_plpymodule.c:518
#, c-format
msgid "invalid SQLSTATE code"
msgstr "无效的SQLSTATE代码"

#: plpy_procedure.c:230
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "触发器函数只能以触发器的形式调用"

#: plpy_procedure.c:234
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python函数不能返回类型%s"

#: plpy_procedure.c:312
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python函数不能接受类型%s"

#: plpy_procedure.c:402
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "无法编译PL/Python函数\"%s\""

#: plpy_procedure.c:405
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "无法编译PL/Python中的匿名代码块"

#: plpy_resultobject.c:121 plpy_resultobject.c:147 plpy_resultobject.c:173
#, c-format
msgid "command did not produce a result set"
msgstr "命令没有产生结果集"

#: plpy_spi.c:60
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "plpy.prepare的第二个参数必须是一个序列"

#: plpy_spi.c:104
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: 在顺序位置%d的类型名称不是string"

#: plpy_spi.c:176
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute期望一个查询或一个计划"

#: plpy_spi.c:195
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute将一个序列作为它的第二个参数"

#: plpy_spi.c:305
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "执行SPI_execute_plan失败: %s"

#: plpy_spi.c:347
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute执行失败: %s"

#: plpy_subxactobject.c:97
#, c-format
msgid "this subtransaction has already been entered"
msgstr "已经进入该子事务"

#: plpy_subxactobject.c:103 plpy_subxactobject.c:161
#, c-format
msgid "this subtransaction has already been exited"
msgstr "已经退出该子事务"

#: plpy_subxactobject.c:155
#, c-format
msgid "this subtransaction has not been entered"
msgstr "该子事务仍没有进入"

#: plpy_subxactobject.c:167
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "没有子事务可以退出"

#: plpy_typeio.c:591
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "无法为十进制构造函数导入模块"

#: plpy_typeio.c:595
#, c-format
msgid "no Decimal attribute in module"
msgstr "模块中没有小数位属性"

#: plpy_typeio.c:601
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "由numeric数值到Decimal小数转换失败"

#: plpy_typeio.c:915
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "无法创建Python对象的字节表达式"

#: plpy_typeio.c:1063
#, c-format
msgid "could not create string representation of Python object"
msgstr "无法创建Python对象的字符串表达式"

#: plpy_typeio.c:1074
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "无法将Python对象转换为cstring: Python字符串表达式可能包含空字节"

#: plpy_typeio.c:1183
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "数组的维数超过最大允许值(%d)"

#: plpy_typeio.c:1187
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "无法确定函数返回值的序列长度"

#: plpy_typeio.c:1190 plpy_typeio.c:1194
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "数组的大小超过了最大允许值"

#: plpy_typeio.c:1220
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "带有数组返回类型的函数返回值不是一个Python序列"

#: plpy_typeio.c:1266
#, c-format
msgid "wrong length of inner sequence: has length %d, but %d was expected"
msgstr "内部序列的长度错误：长度为%d，但应为%d"

#: plpy_typeio.c:1268
#, c-format
msgid "To construct a multidimensional array, the inner sequences must all have the same length."
msgstr "要构造多维数组，内部序列的长度必须相同."

#: plpy_typeio.c:1347
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "有缺陷的记录常量: \"%s\""

#: plpy_typeio.c:1348
#, c-format
msgid "Missing left parenthesis."
msgstr "缺少一个左括弧"

#: plpy_typeio.c:1349 plpy_typeio.c:1550
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "要返回数组中的复合类型，请将复合类型作为Python元组返回，例如 \"[('foo',)]\"."

#: plpy_typeio.c:1396
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "在映射中没有找到键\"%s\""

#: plpy_typeio.c:1397
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr "为了在一列中返回空值, 需要在列的后面对带有已命名键的映射添加值None"

#: plpy_typeio.c:1450
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "所返回序列的长度与在记录中列的数量不匹配"

#: plpy_typeio.c:1548
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "在Python对象中不存在属性\"%s\""

#: plpy_typeio.c:1551
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr "为了在一列中返回空值, 需要让返回的对象在带有值None的列后面的带有已命名属性"

#: plpy_util.c:35
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "无法将Python中以Unicode编码的对象转换为PostgreSQL服务器字节码"

#: plpy_util.c:41
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "无法从已编码字符串里提取相应字节码值"
